redis:
    image: redis
    ports:
        - 6379:6379
db:
    image: orchardup/postgresql
    ports:
        - 5432:5432
web:
    build: ./api
    volumes:
        - .:/code
    ports:
        - 5000:5000
        - 81:81
    links:
        - db
    environment:
        DEBUG: 'True'
        SECRET_KEY: __filler__
        SMTP_USERNAME: __filler__
        SMTP_PASSWORD: __filler__
        SMTP_SENDER_NAME: __filler__-mail
        SMTP_SENDER_EMAIL: __filler__.hp@gmail.com
        SMTP_HOST: __filler__-smtp.us-east-1.amazonaws.com
        SMTP_PORT: __filler__


webapp:
    build: ./webapp
    volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
    ports:
        - '8080:80'
    environment:
        - NODE_ENV=development

test-ci:
    build: ./webapp
    command: yarn test-ci
    dockerfile: Dockerfile-test