redis:
    image: redis
    ports:
        - 6379:6379
db:
    image: orchardup/postgresql
    ports:
        - 5432:5432
web:
    build: ./api
    command: python ./api/run.py runserver -h 0.0.0.0 -p 5000
    volumes:
        - .:/code
    ports:
        - 5000:5000
    links:
        - db
    environment:
        DEBUG: 'True'
        SECRET_KEY: asdklfjeoja039rjdlkjfaoi3rdk
        SMTP_USERNAME: __filler__
        SMTP_PASSWORD: __filler__
        SMTP_SENDER_NAME: __filler__
        SMTP_SENDER_EMAIL: __filler__
        SMTP_HOST: __filler__
        SMTP_PORT: __filler__

webapp:
    build: ./webapp
    volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
    ports:
        - '8080:80'
    environment:
        - NODE_ENV=development